# Generated by Django 4.2.13 on 2024-06-22 23:17

from django.db import migrations, models
import django_ckeditor_5.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog_artical',
            fields=[
                ('blog_artical_id', models.AutoField(primary_key=True, serialize=False)),
                ('blog_artical_title', models.CharField(max_length=100)),
                ('blog_artical_subheadeing', models.CharField(max_length=200)),
                ('blog_artical_body', django_ckeditor_5.fields.CKEditor5Field(verbose_name='Text')),
            ],
        ),
        migrations.CreateModel(
            name='Test_animal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('animal_name', models.CharField(max_length=100)),
                ('animal_species', models.CharField(max_length=100)),
            ],
        ),
    ]
