# Generated by Django 4.2.13 on 2024-06-22 23:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Blog_artical',
            new_name='Project_artical',
        ),
        migrations.RenameField(
            model_name='project_artical',
            old_name='blog_artical_body',
            new_name='project_artical_body',
        ),
        migrations.RenameField(
            model_name='project_artical',
            old_name='blog_artical_id',
            new_name='project_artical_id',
        ),
        migrations.RenameField(
            model_name='project_artical',
            old_name='blog_artical_subheadeing',
            new_name='project_artical_subheadeing',
        ),
        migrations.RenameField(
            model_name='project_artical',
            old_name='blog_artical_title',
            new_name='project_artical_title',
        ),
    ]
