# Generated by Django 4.2.13 on 2024-07-25 03:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_project_artical_project_artical_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Test_animal',
        ),
    ]
