# Generated by Django 4.2.13 on 2024-09-08 04:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_delete_test_animal'),
    ]

    operations = [
        migrations.AddField(
            model_name='project_artical',
            name='project_artical_date_added',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project_artical',
            name='project_artical_date_updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
