# Generated by Django 4.2.13 on 2024-06-22 23:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Project_artical',
            new_name='Blog_artical',
        ),
    ]
