# Generated by Django 4.2.13 on 2024-07-25 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_rename_project_artical_blog_artical'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog_artical',
            name='blog_tile_img',
            field=models.ImageField(default='default.jpg', upload_to='blog_images/'),
        ),
    ]
