# Generated by Django 4.2.13 on 2024-09-16 08:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_blog_artical_blog_tile_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog_artical',
            name='blog_artical_date_added',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='blog_artical',
            name='blog_artical_date_updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
